version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5175:5175"
    volumes:
      - .:/app
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - .:/app

  finalapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_DOMAIN="https://7vlx93vd-5175.usw3.devtunnels.ms"
