version: "3"

services:
  instance2:
    build:
      context: ./instance2
      dockerfile: Dockerfile
    mem_limit: 512m # Sets hard memory limit
    # or
    mem_reservation: 256m # Sets soft memory limit
    environment:
      - AWS_IOT_ENDPOINT=a2racyjm6zpt4f-ats.iot.us-east-1.amazonaws.com
      - CERT_FILEPATH=certificate.pem
      - PRI_KEY_FILEPATH=private.key
      - CA_FILEPATH=root-CA.crt
      - CLIENT_ID=adrian_original
      - TOPIC_SUB=dronautica/dataX/58e7
      - TOPIC_PUB=dronautica/dataY/e228
      - TOPIC_ACT=dronautica/data/Dronautica
      - DRONE_NAME=adrian_original
      - DRONE_ID=fffd
      - BASE_LOCATION_LAT=18.489543074164387
      - BASE_LOCATION_LNG=-97.39278599921742
