version: "3"

services:
  notifications:
    build: .
    container_name: notifications
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  redisDashboard:
    image: rediscommander/redis-commander:latest
    container_name: redisDashboard
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=remote:dronautica-notifications-trnocq.serverless.use1.cache.amazonaws.com:6379
