version: "3"

services:
  authentication:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: auth
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - authServer

  mongodbDashboard:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - authServer

networks:
  authServer:
    driver: bridge

volumes:
  mongodb_data:
