export const DashboardEndpoints = {
    getProfilesEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/profiles",
    setProfileStatus: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/profiles/state",
    createProfileEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/profiles",
    getInstancesEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/instances",
    getInstanceEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/instances/item",
    createInstanceEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/instances",
    getDeliveriesEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/delivery/trips",
    getDeliveryDetailsEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/delivery/trips/item",
    createDeliveryTripEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/delivery/trips",
    confirmDeliveryTripEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/delivery/trips/confirm",
    verifyDeliveryTripEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/delivery/trips/verify",
    cancelDeliveryTripEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/delivery/trips/final/cancel",
    acceptDeliveryTripEndpoint: "https://hags70h3uh.execute-api.us-east-1.amazonaws.com/shjs/aviren/delivery/trips/final/accept",
}